title: lucas li
baseurl: /lucasli
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/blog/page:num"

disqus_shortname: lucaslionline




gallery:
- {name: "dan_stevens", size: "1080x1160", txt: "Dan Stevens, 11 Sep 2015"}
- {name: "bowing_to_him", size: "1500x1000", txt: "Bowing To Him, 28 Feb 2015"}
- {name: "parker_ellis", size: "1150x1250", txt: "Parker Ellis, 04 Oct 2014"}
- {name: "leonardo_dicaprio", size: "1150x1050", txt: "Leonardo Dicaprio, 18 Jul 2014"}
- {name: "brokeback_mountain", size: "1500x1000", txt: "Brokeback Mountain, 05 Jun 2014"}


#--------------------------------
# Miscellaneous Section
music:
- {name: "Mighty To Save", by: "Hillsong United", src: Hillsong_United-Mighty_To_Save}
- {name: "Oceans", by: "Hillsong United", src: Hillsong_United-Oceans}
- {name: "In Christ Alone", by: "Newsboys", src: Newsboys-In_Christ_Alone}
- {name: "Above All", by: "Michael W. Smith", src: Michael_W._Smith-Above_All}
- {name: "10,000 Reasons", by: "Matt Redman", src: Matt_Redman-10000_Reasons}
- {name: "Fires", by: "Matt Redman", src: Matt_Redman-Fires}


bookmarks:
- {name: Covenant Church, url: "http://www.covenantepc.org"}
