title: Lucas Li
baseurl: /lucasli
markdown: kramdown
# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "questions/page:num"

disqus_shortname: lucaslionline



#--------------------------------
# Miscellaneous Section

photos:
- {name: 1, txt: }
- {name: 2, txt: }


music:
- {name: "10,000 Reasons", by: "Matt Redman", src: Matt_Redman-10000_Reasons}
- {name: "Fires", by: "Matt Redman", src: Matt_Redman-Fires}


bookmarks:
- {name: Covenant Church, url: "http://www.covenantepc.org"}

